from exceptions import Exception


class MyException(Exception):
    pass